<img src="https://user-images.githubusercontent.com/7065401/39118381-910eb0c2-46e9-11e8-81f1-a5b897401c23.jpeg"
    style="width:300px; float: right; margin: 0 40px 40px 40px;"></img>

# Numpy: Numeric computing library

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.

NumPy major contributions are:

* Efficient numeric computation with C primitives
* Efficient collections with vectorized operations
* An integrated and natural Linear Algebra API
* A C API for connecting NumPy with libraries written in C, C++, or FORTRAN.

Let's develop on efficiency. In Python, **everything is an object**, which means that even simple ints are also objects, with all the required machinery to make object work. We call them "Boxed Ints". In contrast, NumPy uses primitive numeric types (floats, ints) which makes storing and computation efficient.

In [23]:
import numpy as np

In [24]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [25]:
np.array([1.1,2.2,3,4])


array([1.1, 2.2, 3. , 4. ])

Numpy sẽ convert tất cả phần tử sang kiểu dữ liệu cao nhất có trong array

In [26]:
np.array([1.1,2.2,3,4], dtype  = 'float32')

array([1.1, 2.2, 3. , 4. ], dtype=float32)

In [27]:
np.array([1.1,2.2,3,4], dtype  = 'int')

array([1, 2, 3, 4])

In [28]:
X = np.array([1.1,2.2,3,4])

In [29]:
type(X)

numpy.ndarray

In [30]:
X.shape

(4,)

In [31]:
X.ndim

1

In [32]:
X.dtype

dtype('float64')

# Creating Numpy Array from Scratch

In [33]:
np.zeros([2,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
#Tạo 1 mảng range từ 0 , 20 với step = 2
np.arange(0, 21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [38]:
np.full([2,3],9)

array([[9, 9, 9],
       [9, 9, 9]])

In [39]:
#tạo array có các khoảng cách nhau đoạn tuyến tính ( linear space)
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# Random

In [42]:
np.random.random((4,4))

array([[0.61236576, 0.67676693, 0.07651314, 0.03726531],
       [0.51571521, 0.16289978, 0.24708676, 0.55355786],
       [0.50115584, 0.00323359, 0.85327592, 0.59310443],
       [0.6660369 , 0.22428733, 0.55796987, 0.41217831]])

In [45]:
#Seed for reproducibility
#muốn chạy random bao nhiêu lần thì nó đều ra kết quả như giá trị chạy đầu tiên
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [48]:
np.random.normal(0,1, (3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

In [53]:
np.random.randint(3,4, (4,5))

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [54]:
np.random.rand(3,4,5)

array([[[0.45615033, 0.56843395, 0.0187898 , 0.6176355 , 0.61209572],
        [0.616934  , 0.94374808, 0.6818203 , 0.3595079 , 0.43703195],
        [0.6976312 , 0.06022547, 0.66676672, 0.67063787, 0.21038256],
        [0.1289263 , 0.31542835, 0.36371077, 0.57019677, 0.43860151]],

       [[0.98837384, 0.10204481, 0.20887676, 0.16130952, 0.65310833],
        [0.2532916 , 0.46631077, 0.24442559, 0.15896958, 0.11037514],
        [0.65632959, 0.13818295, 0.19658236, 0.36872517, 0.82099323],
        [0.09710128, 0.83794491, 0.09609841, 0.97645947, 0.4686512 ]],

       [[0.97676109, 0.60484552, 0.73926358, 0.03918779, 0.28280696],
        [0.12019656, 0.2961402 , 0.11872772, 0.31798318, 0.41426299],
        [0.0641475 , 0.69247212, 0.56660145, 0.26538949, 0.52324805],
        [0.09394051, 0.5759465 , 0.9292962 , 0.31856895, 0.66741038]]])

# Array index and Slicing

## One-dimensional subarray

In [56]:
X1 = np.random.randint(20,size = 6)

In [57]:
X1

array([19, 16,  0,  0,  6, 19])

In [58]:
X1[4]

6

In [59]:
X1[:-1]

array([19, 16,  0,  0,  6])

## Multi-dimension array

In [65]:
X2 = np.random.randint(10, size = (2,3))

In [66]:
X2

array([[8, 8, 3],
       [8, 2, 8]])

## Slicing

#### X[start:stop:step]

In [69]:
X2[0:1]

array([[8, 8, 3]])

In [86]:
X2[0:1, 0:2]

array([[8, 8]])

In [89]:
X2[:2, :2]

array([[8, 8],
       [8, 2]])

In [81]:
X1 = np.array([1,3,4,52,4])


In [84]:
X1[2 : 6]

array([ 4, 52,  4])

In [85]:
X1[::2]

array([1, 4, 4])

## Reshaping of Array and Transpose

In [96]:
grid = np.arange(1,10)

grid.shape

(9,)

In [92]:
grid.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
grid.reshape((3,3)).T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Array Concantenation and Splitting

### Concantenation

In [99]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [102]:
np.concatenate((x,y), axis = 0)

array([1, 2, 3, 3, 2, 1])

In [120]:
x = np.random.randint(5,size = (3,3))
y = np.random.randint(5,size = (3,3))

In [132]:
x

array([[3, 1, 4],
       [2, 2, 0],
       [1, 0, 4]])

In [133]:
y

array([[0, 3, 2],
       [0, 0, 1],
       [1, 0, 3]])

In [129]:
np.concatenate((x,y), axis = 0)

array([[3, 1, 4],
       [2, 2, 0],
       [1, 0, 4],
       [0, 3, 2],
       [0, 0, 1],
       [1, 0, 3]])

In [124]:
np.concatenate((x,y), axis = 0).shape

(6, 3)

In [130]:
np.concatenate((x,y), axis = 1)

array([[3, 1, 4, 0, 3, 2],
       [2, 2, 0, 0, 0, 1],
       [1, 0, 4, 1, 0, 3]])

In [125]:
np.concatenate((x,y), axis = 1).shape

(3, 6)

In [136]:
#vstack ( vertical stack)
#Nối theo chiều ngang ( thêm hàng)
x = np.array([1,2,3])
y = np.array([[0, 3, 2],
       [0, 0, 1],
       [1, 0, 3]])

In [138]:
np.vstack((x,y))

array([[1, 2, 3],
       [0, 3, 2],
       [0, 0, 1],
       [1, 0, 3]])

In [143]:
#hstack(horixontal stack)
#nối theo chiều dọc ( thêm dòng)
y = np.array([0, 3, 2],
       )
np.hstack((x,y))

array([1, 2, 3, 0, 3, 2])

### Splitting array

In [144]:
x = np.array([1,2,3,4,21,42])

In [145]:
np.split(x, [3,5])

[array([1, 2, 3]), array([ 4, 21]), array([42])]

In [146]:
x1,x2,x3 = np.split(x, [3,5])

# Broadcasting and Vectorize operations

### Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.

![image-broadcasting](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

### Dễ hiểu hơn là numpy sẽ nhân bản các phần tử sao cho 2 ma trận sẽ có cùng chiều hoặc có số chiều phù hợp để thực hiện các phép tính

In [147]:
a = np.arange(3)

In [148]:
a

array([0, 1, 2])

In [149]:
a + 5

array([5, 6, 7])

In [150]:
b = np.ones((3,3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [151]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])