# Numpy

## Creating Numpy arrays from lists

In [129]:
import numpy as np

In [130]:

np.array([1,2,3,4])

array([1, 2, 3, 4])

In [131]:
a2 =  np.array([[1,2,3],
               [4,5,6]])

In [132]:
type(a2)

numpy.ndarray

In [133]:
a2.shape

(2, 3)

In [134]:
a2.dtype

dtype('int64')

In [135]:
a2.ndim

2

In [136]:
a2.size

6

In [137]:
np.zeros([2,3],dtype = int)

array([[0, 0, 0],
       [0, 0, 0]])

In [138]:
np.ones([2,3],dtype = int)

array([[1, 1, 1],
       [1, 1, 1]])

In [139]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [140]:
np.full((2,2),1.2)

array([[1.2, 1.2],
       [1.2, 1.2]])

In [141]:
#create an array of five values evenly spaced between 0 and 1
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

### random

In [142]:
np.random.random([2,2])

array([[0.33800761, 0.67475232],
       [0.31720174, 0.77834548]])

In [143]:
#seed for reproducibility
np.random.seed(0)
np.random.random([2,2])

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318]])

In [144]:
np.random.normal(0,1,(3,3))

array([[ 1.86755799, -0.97727788,  0.95008842],
       [-0.15135721, -0.10321885,  0.4105985 ],
       [ 0.14404357,  1.45427351,  0.76103773]])

In [145]:
np.random.randint(0, 10, (4, 5))

array([[8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3],
       [8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9]])

In [146]:
np.random.rand(4,4)

array([[0.94466892, 0.52184832, 0.41466194, 0.26455561],
       [0.77423369, 0.45615033, 0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572, 0.616934  , 0.94374808],
       [0.6818203 , 0.3595079 , 0.43703195, 0.6976312 ]])

## Array indexing & slicing
### One-dimensional subarray

In [147]:
x1 = np.random.randint(20,size = 6)
x1

array([ 9,  3,  6, 11, 14, 18])

In [148]:
x1[4],x1[3],x1[-1]

(14, 11, 18)

### Multi-dimensional array

In [149]:
x2 = np.random.randint(10,size = (3,4))

In [150]:
x2

array([[0, 3, 5, 9],
       [4, 4, 6, 4],
       [4, 3, 4, 4]])

In [151]:
x2[1,3]

4

In [152]:
x2[1,3]=6
x2

array([[0, 3, 5, 9],
       [4, 4, 6, 6],
       [4, 3, 4, 4]])

### Slicing
x[start:stop:step]

In [153]:
x1

array([ 9,  3,  6, 11, 14, 18])

In [154]:
x1[0:3:1]

array([9, 3, 6])

In [155]:
x1[2:4]

array([ 6, 11])

In [156]:
x1[1:6:2]

array([ 3, 11, 18])

In [157]:
x2[:2,:3]

array([[0, 3, 5],
       [4, 4, 6]])

In [158]:
x2[:,:2]

array([[0, 3],
       [4, 4],
       [4, 3]])

### Reshaping of Arrays & Transpose

In [159]:
grid = np.arange(1,10)

In [160]:
grid.shape

(9,)

In [161]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [162]:
x = np.array([1,2,3])

In [163]:
x.shape

(3,)

In [164]:
x.reshape(1,3).shape

(1, 3)

In [165]:
x3 = np.random.randint(0,10,size = (2,2))

In [166]:
x3

array([[8, 4],
       [3, 7]])

In [167]:
x3.T

array([[8, 3],
       [4, 7]])

## Array Concatenation and Splitting

In [168]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [169]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [170]:
grid = np.array([[1,2,3],
                 [4,5,6]])

In [171]:
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [172]:
np.concatenate((grid,grid),axis =1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [173]:
#vstack
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [174]:
#hstack
y = np.array([[1],
             [1]])
np.hstack((y,grid))

array([[1, 9, 8, 7],
       [1, 6, 5, 4]])

## Spliting of arrays

In [175]:
x = np.array([1,2,3,4,5,6])

In [176]:
np.split(x,[3,5])

[array([1, 2, 3]), array([4, 5]), array([6])]

## Broadcasting and Vectorized operations

In [177]:
a = np.arange(3)

In [178]:
a


array([0, 1, 2])

In [179]:
a +5 #broadcasting: Tự đồng điền các phần tử sao cho phù hợp 
# trong việc cộng trừ nhân chia các mảng mà shape k phù hợp cho việc tính toán

array([5, 6, 7])

In [180]:
x = np.ones([3,3])

In [181]:
x


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [182]:
a.shape, x.shape

((3,), (3, 3))

In [183]:
a+x

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [184]:
a*x

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [185]:
a = np.array([1,2,3])
c = np.array([[1],
              [2],
              [3]])

In [186]:
a+c

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

## Manipulating & Comparing Arrays

### Aggergation
Aggergation = performing the same operation on a. number of things

In [187]:
list_number = [1,2,3]
ll = np.array(list_number)



In [188]:
sum(ll) # python sum

6

In [189]:
np.sum(ll) #numpy sum nhanh hon python sum

6

In [190]:
# Create a massive Numpy Array
massive_array = np.random.random(1000)
massive_array[:5]

array([0.33800761, 0.67475232, 0.31720174, 0.77834548, 0.94957105])

In [191]:
massive_array.shape

(1000,)

In [192]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

63.1 µs ± 70.2 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
2.26 µs ± 7.54 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [193]:
np.mean(massive_array)

0.503445254237163

In [194]:
np.max(massive_array)

0.9980254861986478

In [195]:
np.min(massive_array)

5.535686500857118e-05

In [196]:
dog_height=[600,470,430,170,300]
dog_height = np.array(dog_height)
np.var(dog_height), np.std(dog_height)

(21704.0, 147.32277488562318)

## Sorting arrays
np.sort(x) use quick sort algorithm

In [197]:
x = np.random.randint(10,size =4)
x


array([2, 7, 2, 7])

In [198]:
np.sort(x)

array([2, 2, 7, 7])

In [199]:
np.argsort(x) # return index cua cac phan tu da sort trong array ban dau

array([0, 2, 1, 3])

## Sorting along rows or columns
NumPy's soritng algorithm is the ability to sort along specific rows and columns of a multidimensional array using the axis argument

In [200]:
np.random.seed(42)
MatA = np.random.randint(0,10,size=(4,6))

In [201]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [202]:
np.sort(MatA,axis =1) #rows

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [203]:
np.sort(MatA,axis =0) # columns

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

## Linear Algebra (Dai so tuyen tinh)

In [204]:
A = np.random.randint(0,10,size = (3,3))
np.random.seed(0)
A

array([[8, 0, 9],
       [2, 6, 3],
       [8, 2, 4]])

In [205]:
B = np.random.randint(0,10,size = (2,3))
np.random.seed(42)
B

array([[5, 0, 3],
       [3, 7, 9]])

In [206]:
B.dot(A)

array([[ 64,   6,  57],
       [110,  60,  84]])

In [207]:
B@A

array([[ 64,   6,  57],
       [110,  60,  84]])

# Dot Product Example

In [208]:
# Number of jars sold
np.random.seed(0)

sales_amounts = np.random.randint(20,size= (5,3))

In [209]:
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [210]:
#Create current weekly_sales DataFrame
import pandas as pd
weekly_sales = pd.DataFrame(sales_amounts,index = ['Mon','Tue','Wed','Thu','Fri'],
                                          columns  = ["Xoi","Bmy","pho"] )

In [211]:
weekly_sales

Xoi  Bmy  pho
Mon   12   15    0
Tue    3    3    7
Wed    9   19   18
Thu    4    6   12
Fri    1    6    7

In [212]:
# Create price array
prices = np.array([10,12,15])
Xoi_prices = pd.DataFrame(prices.reshape(1,3),index = ["Price"],columns  = ["Xoi","Bmy","pho"])

In [213]:
Xoi_prices

Xoi  Bmy  pho
Price   10   12   15

In [214]:
total_price = weekly_sales.dot(Xoi_prices.T)

In [215]:
total_price

Price
Mon    300
Tue    171
Wed    588
Thu    292
Fri    187

In [216]:
weekly_sales["total_price"] = total_price
weekly_sales    

Xoi  Bmy  pho  total_price
Mon   12   15    0          300
Tue    3    3    7          171
Wed    9   19   18          588
Thu    4    6   12          292
Fri    1    6    7          187